export const CURRENCY_NAMES: Record<string, string> = {
  EUR: "Euro",
  USD: "US Dollar",
  ALL: "Albanian Lek",
  GBP: "British Pound",
  CHF: "Swiss Franc",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Złoty",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  TRY: "Turkish Lira",
  CNY: "Chinese Yuan",
  HKD: "Hong Kong Dollar",
  INR: "Indian Rupee",
  KRW: "South Korean Won",
  MXN: "Mexican Peso",
  NZD: "New Zealand Dollar",
  SGD: "Singapore Dollar",
  THB: "Thai Baht",
  ZAR: "South African Rand",
  ILS: "Israeli Shekel",
  BRL: "Brazilian Real",
  IDR: "Indonesian Rupiah",
  PHP: "Philippine Peso",
  MYR: "Malaysian Ringgit",
  ISK: "Icelandic Króna"
};